Pet.create(name: "Akida", species: "dog", breed: "husky", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44048568/1/?bust=1550549550&width=1080", description: "This blue-eyed beauty is 43 pounds right now but she is on the thin side and needs to gain a bit of weight. She is very loving and calm. She is very sweet and likes to watch what’s happening before she jumps in. She’s good with other dogs and people and great in the car. Did I mention she is very chill? VERY chill. Akida may be a good “starter Husky”")

Pet.create(name: "Ace", species: "dog", breed: "husky", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44048572/1/?bust=1550549553&width=1080", description: "Ace is a 6ish month old puppy that still has quite a bit of growing to do but easy going for a pup his young age. He is potty trained, crate trained (sleeps quietly at night in his crate), walks well on leash and is very social with people and dogs. He knows to sit and shake! Needless to say Ace is dark, tall and handsome with a personality to match. This heartthrob will not last long!")

Pet.create(name: "Tilly", species: "dog", breed: "husky", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44043000/1/?bust=1550466305&width=1080", description: "Tilly is about a year old (guessing) and currently skinny at 32 pounds. While she needs to put on some weight, she will stay petite. Tilly is fairly timid, as she is new to rescue and still figuring out the big wide world, but she will always be a gentle soul. She is a quick study and very trusting of people so if you show her that something isn’t so scary, she’ll follow and be a pro by encounter number 2. Tilly loves to cuddle on the couch and be with her people. While she would be fine at home while you’re away, she is also a great candidate to be an office dog as she is happiest napping/chilling out by your side. She would also make a great companion for outdoor dining and other adventures. While she hasn’t shown a lot of interest in engaging in play and sometimes can be timid, she’s been very friendly with all other dogs she’s met. She would be happy in a house as the only dog or with some siblings. Given a home with a little patience, love and some comfy cushions, Tilly will make an awesome companion!")

Pet.create(name: "Eris", species: "dog", breed: "husky", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44037103/1/?bust=1550549558&width=1080", description: "Born December 13th. He is not available at this time, but will be in about a month. My parents are Chance and Roxie also on the website.")

Pet.create(name: "Moon Doggie", species: "dog", breed: "husky", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43988444/1/?bust=1550129865&width=1080", description: "This is one handsome rascal! What a character - with his baritone bark and habit of carrying his food bowl back to you when done (please sir, can I have some more?). Tough-of-war is one of Moon Doggie's favorite games - either with dogs or people - followed closely by wrestling with the other dogs in the house. Moon Doggie loves going on walks and is good on leash.
As you probably noticed - Moon Doggie is blind. He came into rescue with severe glaucoma - the pressure was so high both eyes had ruptured. The pain made him quiet and sedate. Once the eyes were removed and the pain stopped, he has become his effervescent, rascally self!")

Pet.create(name: "Char", species: "dog", breed: "greyhound", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43821988/1/?bust=1548017078&width=1080", description: "Char born Feb 2015 is a sweet friendly girl not good with cats. She is confident and should adjust easily to her new environment.")

Pet.create(name: "Deuce", species: "dog", breed: "greyhound", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43821884/1/?bust=1548016793&width=1080", description: "Deuce is youngster born May of 2017. He will be good with cats. He is young and playful which helps him gain confidence in new situations. He will be quick learner.")

Pet.create(name: "Jack", species: "dog", breed: "greyhound", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43821739/1/?bust=1548016307&width=1080", description: "Jack was born Feb 2016 and is good with cats. Jack is a super sweet boy. Although not pushy, he would love to fawn over you day and night.")

Pet.create(name: "Jack", species: "dog", breed: "greyhound", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43821739/1/?bust=1548016307&width=1080", description: "Jack was born Feb 2016 and is good with cats. Jack is a super sweet boy. Although not pushy, he would love to fawn over you day and night.")

Pet.create(name: "Liam", species: "dog", breed: "maltese", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43974920/1/?bust=1550091522&width=1080", description: "Liam is a 2 year old Maltipoo who weighs 13 lbs. He was a surrender to our rescue because the family was moving and could not take him with them. They had him since he was a puppy. Liam has a non-shedding coat that is an option for those with allergies or those who just want a dog that does not shed. Liam will require regular grooming. We will require a home that demonstrates readiness to groom.
Liam is fostered with both big and small dogs and gets along great with them. Liam is a super playful and loving boy. He is nervous initially because this is all brand new for him. But generally within moments, he adjusts to his new surroundings if his people are confident. In his foster home he waltzed in and it was if he was home! He is as happy as a clam. Liam is a big cuddle bug. But he also has a super spunky personality. He loves to go out and play, and run around and make new friends. He will need a home prepared to bring in a spunky pup.")

Pet.create(name: "Mistletoe", species: "dog", breed: "maltese", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43761231/1/?bust=1550091518&width=1080", description: "Mistletoe is a 2 year old Maltese mix, weighing 13 lbs, who we rescued from a shelter. He was surrendered to the shelter by a family member who admitted that others in the family had abused him. He had been kicked and mistreated in his home and as a result was not doing well in the shelter environment and was in danger of being euthanized, so we had to step him and save his life.
Mistletoe does well with confident owners who don't let him take charge and just let him be a dog. He needs a dog savvy, knowledgeable home. He isn't great on a leash because he has a tendency to grab at people's ankles when they walk past him too quickly, almost like a herding dog. He will need leash training from an owner who can be a strong leader for him. Once he is comfortable with his people, he is a sweet and loving boy who just wants to be near you. He's had a hard life, but he still loves getting attention. Under his tough exterior, he's just a lover-boy.")

Pet.create(name: "Olaf", species: "dog", breed: "maltese", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43874779/1/?bust=1548651277&width=1080", description: "For an experienced dog owner Olaf would make a loving and intelligent companion. He is very treat motivated, benefits immensely from structure and routine, bonds strongly with his trainer, and when he trusts you is very affectionate and cuddly. He also does great in the car and enjoys his walks and going to new places, with the right person he could make a great travel dog! He does have a low threshold for stimulation however and would need a person who can read his body language and understand when he is at his limit. He would do best in a home with either no other dogs or a very mellow companion who would not push his limits. He should also be in a home with no young children at all, or potentially with older children (above the age of 14) who would understand his need for boundaries and space.")

Pet.create(name: "Rajah", species: "cat", breed: "bengal", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/38300919/2/?bust=1496810680&width=1080", description: "Please meet Rajah, a lovable, fearless male 1 year old Bengal mix. Although Rajah lives in an indoor/outdoor safely enclosed cat area at his foster parents' house, he would love a home to call his very own. Could that be yours?")

Pet.create(name: "Donovan", species: "cat", breed: "bengal", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/41497476/6/?bust=1542764174&width=1080", description: "I am a very handsome boy who would love to be the sole object of attention in the right home. Though I adore humans, I'm not that keen on other animals. I need to be an only child. I am very bonded to people and want to be part of the family. I love attention, but don't like to be picked up or restrained. I will sit next to you, lie on your lap, follow you around the house, and sleep next to you. I enjoy chasing a laser light or feather on a string, and also enjoy playing with toys on my own. I purr a lot and makes biscuits all the time. If all that sounds good to you, let's meet, and see if we might make the perfect pair.
I will be loyal and your best friend!")

Pet.create(name: "Margie", species: "cat", breed: "bengal", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/43344360/6/?bust=1542768421&width=1080", description: "I was rescued when a kind man took me home from where he worked; I had been wandering around looking for food and attention from humans. I'm really cute and healthy and very playful. I like to make biscuits in the air on my favorite blanket! I like to have conversations with my foster family. Come meet me and take me home for the holidays! I’m softer than Cashmere, too!")

Pet.create(name: "Twix", species: "cat", breed: "bengal", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/35114491/1/?bust=1463191376&width=1080", description: "Is is possible to be any cuter than this? What a precious little one. This handsome boy has gorgeous markings. He is such a 'ham'....if you want to be entertained, this is the baby for you!")

Pet.create(name: "Ava", species: "cat", breed: "tuxedo", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44061505/2/?bust=1550702254&width=1080", description: "Ava is one seriously fun kitty ! She really enjoys play time , she needs a home with tons of love and interaction ! She really enjoys playing with her siblings, she enjoys a good game of chase ! Could you make her dreams come true and be her forever family?")

Pet.create(name: "Oreo", species: "cat", breed: "tuxedo", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44046214/1/?bust=1550529314&width=1080", description: "He is the sweetest boy. He loves attention. He does great with other animals! He will make a wonderful pet.")

Pet.create(name: "Dexter", species: "cat", breed: "tuxedo", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44045478/3/?bust=1550519136&width=1080", description: "Dexter is a very dapper little tuxedo kitty with glowing copper eyes. He is extremely playful, and likes to sleep in bed with you at night. He loves a good massage, and has a giant purr. He is a jumper and a climber, and loves to play tug of war. If you are looking for a kitty who wants to interact with you frequently, this little guy is your man!")

Pet.create(name: "Grandisimo", species: "cat", breed: "tuxedo", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44031345/1/?bust=1550336512&width=1080", description: "He has the fluffiest white bib and socks and amazing green eyes with a hint of blue. He has a jagged ear which tells us he fended for himself outside prior to being rescued. He is laid back, but is extremely sweet and loves attention and also enjoys playing. He gets along well with his feline roommates as long as they don't bother him. He is FIV+ which is the Feline Immunodeficiency Virus. It is only contagious to other cats. It means his immune system is a little weaker than average, but most cats with FIV live long healthy lives if they are in a safe, indoor only, calm environment.")

Pet.create(name: "Gordon", species: "cat", breed: "tuxedo", image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/44029902/1/?bust=1550335878&width=1080", description: "Gordon is a big, fluffy boy at 16 pounds. He's not big on playtime, but he is always the first to the cat bowl for food. He is definitely a lover not a fighter and would like nothing more than to Netflix and chill. He is very sweet and gentle with his cousin Filbert, and they need to be adopted together. He loves to have company especially while sleeping. He's looking for a human that will enjoy brushing him to keep his coat beautiful and help him on his weight loss journey. He is fine with calm kids over 10, but no dogs. We estimate he was born around April 15, 2017")